### ISSUE TITLE
Help with Parse Method

### ISSUE THREAD

**Issue by juspch** [Loksly/nodehl7#11]
hello, im having some difficulty using your package in parsing an HL7 string received via tcp.

Whenever i try using the parse method, i always get an undefined value, so im assuming that its not even reading my string correctly at all. perhaps you could put up an example on how to properly use the parse method just like you did with the parsefile method?

**Comment by Loksly** [comment]
Hi juspch,

I've just added an example https://github.com/Loksly/nodehl7/blob/master/test/testHl7libparse.js .
It's very easy to invoke:
`hl7parser.parse(originalMessage, testfile, function(err, message){ /* add your code here */ }`

Please check the `err` variable.

**Comment by Loksly** [comment]
I'm going to close the _issue_. Reopen it if you need more help or open a new one if you need to.
