### ISSUE TITLE
How to export HL7 message to string?

### ISSUE THREAD

**Issue by rajesh-vi** [Loksly/nodehl7#2]
I have used this library to parse HL7 string message but now want to modify some fields and then need to export back to HL7 as string, How can I do it using this library? any hint?

Thanks for the support

**Comment by Loksly** [comment]
Hi Rajesh!

This library does not support by now serialization back from Object to HL7 Message, although I guess it has enough information to do it.

I've just uploaded a non-perfect example of the code that can do what you are asking for:
https://github.com/Loksly/nodehl7/blob/master/test/testHl7Serialize.js

As an important notice: It lacks from escaping delimiters. Anyway this is a good enough approach.
I hope it suits you.

Thanks for using it and for your feedback.

**Comment by rajesh-vi** [comment]
Hi Loksly,

thanks for the hint, I will check it...
