### ISSUE TITLE
Only MSH segment is working

### ISSUE THREAD

**Issue by gvso** [Loksly/nodehl7#3]
When trying to get the segments using the code in the description and the ADTA01.adm file from test, only the MSH segment works and return a HL7Segment object. Any other segment (EVN, PID, NK1, PV1) returns null.

**Comment by Loksly** [comment]
sorry for that, let me a day to get through this and answer to this issue.

**Comment by Loksly** [comment]
Hi @GVSO !

I've just added some tests and it seems to be working, can you review them and send me back the code that fails?

This test might fit your needs:
https://github.com/Loksly/nodehl7/commit/61ab82dff89365a90be319938b10bfc3a44b254e

```js
it('expect to parse all segments on small files', function(done){
	hl7parser.parseFile(path.join(__dirname, './testfiles/ADTA01.adm'),
		function(err, message){
			expect(err).to.be.an('null');
			expect(message).to.have.a.property('segments');
			var expectedSegments = ['MSH', 'EVN', 'PID', 'NK1', 'PV1'];
			expectedSegments.forEach(function(segmentname){
				expect(message.get(segmentname)).to.be.an('object');
			});
			done();
		}
	);
});
```

**Comment by Loksly** [comment]
I guess it worked. I'm going to close this. Open a new one if you are still in trouble
